#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;
use XTeam\Console\Command\PokeUserCommand;

$application = new Application();
$application->add(new PokeUserCommand());
$application->run();
